lock_web_interface/lock_web_interface/urls.py
from django.contrib import admin
from django.urls import path

from lock_web_interface.views import home, api, admin as management

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.home, name="home"),
    path('home', home.home, name="home"),
    path('login', home.login, name="login"),
    path('logout', home.logout, name="logout"),
    path('signup', home.signup, name="signup"),
    path('management', management.ManagementView.as_view(), name="management"),
    path('management/users', management.UserView.as_view(), name="management_users"),
    path('management/toggle_auth', management.OneAuthUsersView.as_view(), name="management_toggle_auth"),
    path('management/login_entries', management.LogEntryView.as_view(), name="management_login_entries"),
    path('api/send_mail', api.send_mail_with_login_code, name="api_send_mail"),
    path('api/one_factor_auth', api.can_authenticate_with_one_factor, name="api_one_factor_auth"),
    path('api/login_entry', api.add_login_entry, name="api_login_entry"),
]

lock_web_interface/lock_web_interface/models.py
import base64
import uuid

from django.db import models

from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

USER_TYPES = (
    ('ADMIN', 'ADMIN'),
    ('REGULAR', 'REGULAR')
)


class MyUser(AbstractUser):
    user_type = models.CharField(max_length=30, choices=USER_TYPES)
    email = models.EmailField(_('adresse email'), blank=False, unique=True)
    birth_date = models.DateField(verbose_name=_('Date de naissance'), default=timezone.now)
    phone = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    user_token = models.UUIDField(editable=True, default=uuid.uuid4)
    one_factor_auth_enabled = models.BooleanField(default=False)
    one_factor_code = models.CharField(max_length=12)
    nfc = models.CharField(max_length=20, null=True)

    EMAIL_FIELD = "email"
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_birth_date(self):
        pass

    def get_one_factor_code(self):
        return base64.b64decode(bytes(self.one_factor_code[1:], 'utf-8')).decode()

    @classmethod
    def generate_random_etan_password(cls):
        password = cls.objects.make_random_password(length=6)
        return password


AUTH_TYPES = (
    ('NFC', 'NFC'),
    ('PASSWORD', 'PASSWORD')
)


class LoginEntry(models.Model):
    date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE, related_name="login_entries")
    auth_type = models.CharField(choices=AUTH_TYPES, max_length=50)


class RecordConfig(models.Model):
    nb_records=models.IntegerField(default=10)

lock_web_interface/lock_web_interface/forms/user_form.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError, MultipleObjectsReturned
from django.utils.translation import gettext_lazy as _
import logging
import base64

from lock_web_interface.models import MyUser

logger = logging.getLogger(__name__)

USER_TYPE_CHOICES = (
    ('ADMIN', 'ADMIN'),
    ('REGULAR_USER', 'REGULAR_USER')
)


class BaseUserForm(forms.Form):
    first_name = forms.CharField(required=True, label=_('Prénom'), widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "Baptiste"}))
    last_name = forms.CharField(required=True, label=_('Nom'), widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "Delrue"}))
    email = forms.EmailField(required=True, label=_('Email'), widget=forms.EmailInput(
        attrs={"class": "form-control input-lg", "placeholder": "azerty@gmail.com"}))
    password1 = forms.CharField(required=True, label=_("Mot de passe"), min_length=8,
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control input-lg", "placeholder": "Mot de passe"}))
    password2 = forms.CharField(required=True, label=_("Confirmer le mot de passe"), min_length=8,
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control input-lg", "placeholder": "Confirmer"}))


class AdminForm(BaseUserForm):

    def clean_password1(self):
        password1 = self.data.get('password1', None)
        password2 = self.data.get('password2', None)

        if password1:
            if password1 != password2:
                self.add_error('password2', _('Les mots de passe sont différents'))
            else:
                try:
                    validate_password(password1)
                except ValidationError as val_errors:
                    self.add_error('password1', val_errors)

        else:
            self.add_error('password1', _('Ce champ est requis'))

        return password1

    def save(self):
        try:
            first_name = self.cleaned_data.get('first_name')
            last_name = self.cleaned_data.get('last_name')
            user_type = "ADMIN"
            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password1')

            user = MyUser.objects.create_user(
                username=email,
                first_name=first_name,
                last_name=last_name,
                email=email,
                user_type=user_type,
                password=password,
                is_active=False
            )
            return user
        except Exception as e:
            logger.error(e)
            raise


class UserForm(BaseUserForm):

    def __init__(self, **kwargs):
        self.user_id = kwargs.pop("user_id")
        super().__init__(**kwargs)
        self.fields['user_id'] = forms.CharField(required=False, widget=forms.HiddenInput(), label="user id",
                                                 initial=self.user_id)
        self.fields.pop('password1')
        self.fields.pop('password2')

    one_factor_code = forms.CharField(required=True, label=_('Code'), widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "code d'authentification à 1 facteur"}))
    username = forms.CharField(required=True, label=_('Username'), widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "Username"}))
    nfc = forms.CharField(required=True, label=_('Code NFC'), widget=forms.TextInput(
        attrs={"class": "form-control input-lg", "placeholder": "code NFC"}))

    def clean(self):
        nfc = self.cleaned_data.get('nfc')
        try:
            MyUser.objects.get(nfc=nfc)
        except MultipleObjectsReturned:
            self.add_error('nfc', "A user with this code already exist")
        except MyUser.DoesNotExist:                                              #ici
            pass
    def save(self):
        try:
            first_name = self.cleaned_data.get('first_name')
            last_name = self.cleaned_data.get('last_name')
            username = self.cleaned_data.get('username')
            user_type = "REGULAR"
            email = self.cleaned_data.get('email')
            password = "azerty123"
            one_factor_code = self.cleaned_data.get('one_factor_code')
            nfc = self.cleaned_data.get('nfc')
            if self.user_id:
                user = MyUser.objects.get(id=self.user_id)
                user.username = username
                user.first_name = first_name
                user.last_name = last_name
                user.email = email
                user.password = password
                user.one_factor_code = base64.b64encode(bytes(one_factor_code, 'utf-8'))
                user.nfc = nfc
                user.save()
            else:
                user = MyUser.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    user_type=user_type,
                    password=password,
                    one_factor_code=base64.b64encode(bytes(one_factor_code, 'utf-8')),
                    nfc=nfc,
                    is_active=False
                )
            return user
        except Exception as e:
            logger.error(e)
            raise

lock_web_interface/lock_web_interface/views/admin.py
import base64

from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage
from django.http import JsonResponse, QueryDict, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
import logging

from lock_web_interface.forms.user_form import UserForm
from lock_web_interface.models import MyUser, LoginEntry, RecordConfig

logger = logging.getLogger(__name__)


class ManagementView(View):

    @classmethod
    def get(cls, request):
        user_page = request.GET.get('page', 1)
        action = request.GET.get('action')
        if action:
            if action == "next":
                user_page = int(user_page) + 1
            else:
                user_page = int(user_page) - 1

        regular_users = MyUser.objects.filter(user_type="REGULAR").order_by('username')
        paginator = Paginator(regular_users, 10)  # 5 liens par page
        try:
            # La définition de nos URL autorise comme argument « page » uniquement
            # des entiers, nous n'avons pas à nous soucier de PageNotAnInteger
            user_pages = paginator.page(user_page)
        except EmptyPage:
            # Nous vérifions toutefois que nous ne dépassons pas la limite de page
            # Par convention, nous renvoyons la dernière page dans ce cas
            user_pages = paginator.page(paginator.num_pages)

        form = UserForm(user_id=None)
        context = {
            "user_pages": user_pages,
            "form": form,
            "action_form": "Ajouter"
        }
        return render(request, 'lock_web_interface/management.html', context=context)



class UserView(View):
    template_name = "lock_web_interface/management/user_template.html"

    @classmethod
    def get(cls, request):
        try:
            user_id = request.GET.get('id')
            user = MyUser.objects.get(id=user_id)
            logger.info(type(user.one_factor_code))
            logger.info(user.one_factor_code)
            initials = {
                'first_name': user.first_name,
                'last_name': user.last_name,
                'email': user.email,
                'username': user.username,
                'one_factor_code': base64.b64decode(bytes(user.one_factor_code[1:], 'utf-8')).decode(),
                'nfc': user.nfc
            }

            context = {
                "form": UserForm(initial=initials, user_id=user_id),
                "action_form": "Modifier"
            } 
            template = render_to_string(
                template_name=cls.template_name,
                request=request,
                context=context
            )
            return JsonResponse(status=200, data={'html': template})
        except Exception as e:
            logger.error(e)
            return JsonResponse(status=500, data={
                "msg": "an error has occured on our end"
            })

    @classmethod
    def post(cls, request):
        try:
            form = UserForm(data=request.POST, user_id=request.POST.get('user_id'))
            logger.info(form.is_bound)
            context = {
                "form": form,
                "action_form": "Modifier" if request.POST.get('user_id') else "Ajouter"
            }
            if form.is_valid():
                form.save()
                return JsonResponse(status=200, data={
                    'msg': "user updated with success"
                })
            else:
                logger.error(form.errors)
                template = render_to_string(
                    template_name=cls.template_name,
                    request=request,
                    context=context
                )
                return JsonResponse(status=400, data={
                    'msg': "form errors",
                    "html": template
                })
        except Exception as e:
            logger.error(e)
            return JsonResponse(status=500, data={
                "msg": "an error has occured on our end"
            })

    @classmethod
    def delete(cls, request):
        try:
            user_id = QueryDict(request.body).get('id')

            MyUser.objects.get(id=user_id).delete()
            return JsonResponse(status=200, data={
                'msg': "user deleted with success"
            })
        except Exception as e:
            logger.error(e)
            return JsonResponse(status=500, data={
                "msg": "an error has occured on our end"
            })


class OneAuthUsersView(View):

    @classmethod
    def post(cls, request):
        try:
            user_id = request.POST.get('id')
            action = request.POST.get('toggled')
            user = MyUser.objects.get(id=user_id)
            logger.info(action)
            if action == 'False':
                user.one_factor_auth_enabled = True

            else:
                user.one_factor_auth_enabled = False
            user.save()
            return JsonResponse(status=200, data={'msg': "factor authentication toggled with success"})
        except User.DoesNotExist:
            return JsonResponse(status=404, data={"msg": "an error has occured on our end"})
        except Exception as e:
            logger.error(e)
            return JsonResponse(status=500, data={
                "msg": "an error has occured on our end"
            })


class LogEntryView(View):

    @classmethod
    def get(cls, request):
        page = request.GET.get('page', 1)
        action = request.GET.get('action')
        if action:
            if action == "next":
                page = int(page) + 1
            else:
                page = int(page) - 1

        entries = LoginEntry.objects.order_by('-date')

        nb_records = request.session.get('nb_records', 5)
        paginator = Paginator(entries, nb_records)  # 5 liens par page
        try:
            entries_pages = paginator.page(page)
        except EmptyPage:
            entries_pages = paginator.page(paginator.num_pages)

        context = {
            'entries_pages': entries_pages,
        }
        return render(template_name='lock_web_interface/login_entries.html', request=request, context=context)

    @classmethod
    def post(cls, request):
        try:
            nb_records = request.POST.get('nb-records', 10)
            logger.info(nb_records)
            try:
                config = RecordConfig.objects.get()               #ici
            except RecordConfig.DoesNotExist:
                config = RecordConfig(nb_records=nb_records)
            config.save()
            logger.info(request.session['nb_records'])
            return cls.get(request)
        except Exception as e:
            logger.error(e)
            return JsonResponse(status=500, data={})

lock_web_interface/lock_web_interface/views/home.py
from django.contrib.auth import authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import login as lg, logout as lo
import logging

from django.urls import reverse

from lock_web_interface.forms.user_form import AdminForm

logger = logging.getLogger(__name__)


def home(request):
    return render(request, "lock_web_interface/home.html")


def login(request):
    if request.method == "GET":
        return render(request, 'lock_web_interface/login.html')
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user and user.user_type == "ADMIN":
            lg(request, user)
            return HttpResponseRedirect(reverse('management'))
        else:
            logger.info('Login failed')
            context = {
                "error": "Email et/ou Mot de passe incorrect"
            }
            return render(request, 'lock_web_interface/login.html', context)
    else:
        logger.info("method not allowed")
        return HttpResponse(405)


def logout(request):
    """
    This function deletes the current user session and log him out
    :param request:
    :return: return an HttpResponse
    """
    lo(request)
    return HttpResponseRedirect(reverse('login'))


def signup(request):
    """
    This function process GET and POST request for signup view
    :param request:
    :return: return an HttpResponse
    """
    if request.method == "GET":
        form = AdminForm()
        return render(request, 'lock_web_interface/signup.html', context={'form': form})
    elif request.method == "POST":
        form = AdminForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('management_users'))
        else:
            logger.error(form.errors)
            return render(request, 'lock_web_interface/signup.html', context={'form': form})
    else:
        logger.info("method not allowed")
        return HttpResponse(405)


def reset_password(request):
    pass

lock_web_interface/lock_web_interface/templates/lock_web_interface/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lock web interface </title>
    <link href="{% static 'libs/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{% static 'libs/bootstrap/bootstrap.min.js' %}"></script>
    {% block css %}
      {% endblock css %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'home' %}">Lock web interface
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
      </ul>
      <div class="d-flex">
          {% if user.is_authenticated %}
            {{user.get_full_name}} &nbsp;
            <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'logout' %}">Logout</a>&nbsp;
          {% else %}
           <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'login' %}">Login</a>&nbsp;
           <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'signup' %}">Signup</a>
          {% endif %}
      </div>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock content %}

    {% block js %}
    {% endblock js %}
</body>
</html>

lock_web_interface/lock_web_interface/templates/lock_web_interface/home.html
{% extends 'lock_web_interface/base.html' %}
{% block content %}
{% endblock %}

lock_web_interface/lock_web_interface/templates/lock_web_interface/login.html
{% extends 'lock_web_interface/base.html' %}
{% block css %}
    <style>
    .login-card{
        min-height: 300px;
        min-width: 500px;
        border-radius: 5px;
        border: 1px solid black;
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
    .login-title{
        font-weight: bold;
        font-size: 22px;
        text-align: center;
        padding-top: 10px;
        padding-bottom: 10px;
        border-bottom: 1px solid black;
    }
    .form-login{
        margin: 3px
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid background">
        <div class="login-card">
            <div class="login-title"> Login </div>
            <div class="login-content">
                {{error}}
                <form class="form-login" action="{% url 'login'%}" method="post">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                      <input type="text" name="username" class="form-control" id="floatingInput" placeholder="nom d'utilisateur" required>
                      <label for="floatingInput">Username</label>
                    </div>
                    <div class="form-floating mb-3">
                      <input type="password" name="password" class="form-control" placeholder="Mot de passe" required>
                      <label for="floatingInput">Password</label>
                    </div>
                    <button type="submit" class="btn btn-success">Envoyer</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

lock_web_interface/lock_web_interface/templates/lock_web_interface/login_entries.html
{% extends 'lock_web_interface/base.html' %}
{% load humanize %}
{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item active"><a href="{% url 'management' %}">Management</a></li>
    <li class="breadcrumb-item active">login records</li>
</ol>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2 style="font-weight: bold" class=""> Login Records</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                    <th scope="col"> Name</th>
                  <th scope="col">Date</th>
                  <th scope="col"> Auth method</th>
                </tr>
              </thead>
              <tbody>
                {% for entry in entries_pages %}
                <tr>
                    <td scope="row">{{entry.get_full_name}}</td>             
                    <td scope="row">{{entry.date}}</td>
                    <td>{{entry.auth_type}}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div>
              <ul class="pagination">
                  {% if entries_pages.has_previous %}
                    <li class="page-item disabled">
                      <a class="page-link" href="?page={{entries_pages.number}}&action=previous">&laquo;</a>
                    </li>
                  {% endif %}
                <li class="page-item active">
                  <a class="page-link" href="#">{{entries_pages.number}} sur {{entries_pages.paginator.num_pages}}</a>
                </li>
                  {% if entries_pages.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{entries_pages.number}}&action=next">&raquo;</a>
                    </li>
                  {% endif %}
              </ul>
            </div>
            <form method="POST" action="{% url 'management_login_entries' %}">
                {% csrf_token %}
              <div class="form-row align-items-center">
                <div class="col-sm-3 my-1">
                  <label class="sr-only" for="nb-records">Records</label>
                  <input type="text" class="form-control" id="nb-records" name="nb-records">
                </div>
                <div class="col-auto my-1">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

lock_web_interface/lock_web_interface/templates/lock_web_interface/management.html
{% extends 'lock_web_interface/base.html' %}
{% block css %}
<style>
    .divider{
        height: 40px;
        width: 2px;
    }
    .toast-right{
        position: fixed;
        right: 50px;
        top: 50px;
        width: 100px;
        min-height: 50px;
        border-radius: 4px;
    }
</style>
{% endblock %}
{% block content %}

<ol class="breadcrumb">
  <li class="breadcrumb-item active"><a href="{% url 'management' %}">Management</a></li>
</ol>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2 style="font-weight: bold" class=""> Users records</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">NFC</th>
                    <th scope="col">One factor auth</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for user in user_pages %}
                <tr>
                  <th scope="row">{{user.get_full_name}}</th>
                  <td>{{user.email}}</td>
                    <td>{{user.nfc|default:""}}</td>
                    <td><a class="toggle-auth" user-id="{{user.id}}" toggled="{{user.one_factor_auth_enabled}}">{{user.one_factor_auth_enabled}}</a></td>
                    <td><a class="user-edit" user-id="{{user.id}}"> Edit</a>&nbsp;<a class="user-delete" user-id="{{user.id}}"> Delete</a>&nbsp;</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div>
              <ul class="pagination">
                  {% if user_pages.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{user_pages.number}}&action=previous">&laquo;</a>
                    </li>
                  {% endif %}
                <li class="page-item active">
                  <a class="page-link" href="#">{{user_pages.number}} sur {{user_pages.paginator.num_pages}}</a>
                </li>
                  {% if user_pages.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{user_pages.number}}&action=next">&raquo;</a>
                    </li>
                  {% endif %}
              </ul>
            </div>
            <button class="btn btn-secondary my-2 my-sm-0">
                <a href="{% url 'management_login_entries' %}" style="text-decoration: none"> Login records</a>
            </button>
        </div>
        <div class="col-md-2 divider"></div>
        <div class="col-md-5 ">
            <h2 style="font-weight: bold" class=""> Add / Edit a user</h2>
            <div class="block-edit-user">
                {% include 'lock_web_interface/management/user_template.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function (){
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        function toast(msg, purpose){
            let t = `<div class="toast-right" class="${purpose}">${msg}</div>`
            $('body').append(t)
        }
        var csrftoken = getCookie('csrftoken');

        function bindFormReset(){
            setTimeout(()=>{
                $('#button-reset-form').unbind('click')
                $('#button-reset-form').bind('click', function (){
                    for ( let elt of $("form input")){
                        elt.value = ""
                    }
                })
            },500)

        }
        bindFormReset()
        function bind_form_event(){
            $('#form-user').on('submit', function (e){
            e.stopPropagation()
            e.preventDefault()

            $.ajax({
                url: "{% url 'management_users' %}",
                method: "POST",
                headers: {'X-CSRFToken': csrftoken},
                dataType: "json",
                data: {
                    'user_id': $('#id_user_id').val(),
                    "first_name": $('#id_first_name').val(),
                    "last_name": $('#id_last_name').val(),
                    "email": $('#id_email').val(),
                    "username": $('#id_username').val(),
                    "one_factor_code": $('#id_one_factor_code').val(),
                    "password1": $('#id_password1').val(),
                    "password2": $('#id_password2').val(),
                    "nfc": $('#id_nfc').val(),
                },
                success: function (res){
                    console.log(res)
                    window.location.reload()
                },
                error: function (err){
                    console.log(err.responseJSON.msg)
                    $('.block-edit-user').html(err.responseJSON.html)
                }
            })
        })
        }
        bind_form_event()
        $('.toggle-auth').each(function (){
           $(this).on('click', function (){
                let userId = $(this).attr('user-id')
                let toggled = $(this).attr('toggled')
                $.ajax({
                    url: "{% url 'management_toggle_auth' %}",
                    method: "post",
                    headers: {'X-CSRFToken': csrftoken},
                    dataType: "json",
                    data: {
                        "id":userId,
                        "toggled": toggled
                    },
                    success: function (res){
                        window.location.reload()
                    },
                    error: function (err){
                        console.log(err.responseJSON.msg)
                    }
                })
            })
        })
        $('.user-edit').each(function (){
           $(this).on('click', function (){
                let userId = $(this).attr('user-id')
                $.ajax({
                    url: "{% url 'management_users' %}",
                    method: "get",
                    data: {
                        "id":userId,
                    },
                    success: function (res){
                        $('.block-edit-user').html(res.html)

                        bind_form_event()
                        bindFormReset()
                    },
                    error: function (err){
                        console.log(err.responseJSON.msg)
                    }
                })
            })
        })
        $('.user-delete').each(function (){
           $(this).on('click', function (){
                let userId = $(this).attr('user-id')
                $.ajax({
                    url: "{% url 'management_users' %}",
                    method: "delete",
                    headers: {'X-CSRFToken': csrftoken},
                    data: {
                        "id":userId,
                    },
                    success: function (res){
                        window.location.reload()
                    },
                    error: function (err){
                        console.log(err.responseJSON.msg)
                    }
                })
            })
        })

    })
</script>
{% endblock %}